[package]
name = "tensor"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
polars = { version = "0.46", features = ["lazy", "csv", "to_dummies"] }
csv = "1.2"
rand_distr = "0.4"
indicatif = "0.17"
nalgebra = "0.32"

[lib]
name = "dqtensor"
path = "src/lib.rs"
